language: python
python:
    - "3.6.1"
before_install:
    - chmod u+x tests/*.py
    - chmod u+x **/*.py
install:
    - pip install -r requirements.txt
script:
    - tests/runCompleteTestSuite.py